# Example parameters for a UART connection to the Easy IMU module.
eimu_ros:
  ros__parameters:
    # port: "/dev/serial/by-path/pci-0000:00:14.0-usb-0:1.3:1.0-port0"
    port: "/dev/ttyACM0"
    frame_id: "imu"
    publish_frequency: 50.0
    world_frame_id: 1  # 0 - NWU,  1 - ENU,  2 - NED
    publish_tf_on_map_frame: true

    use_static_covariances: false

    static_covariance_orientation: [0.001, 0.0, 0.0, 
                                    0.0, 0.001, 0.0, 
                                    0.0, 0.0, 0.001]

    static_covariance_angular_velocity: [0.001, 0.0, 0.0, 
                                         0.0, 0.001, 0.0, 
                                         0.0, 0.0, 0.001]

    static_covariance_linear_acceleration: [0.001, 0.0, 0.0, 
                                            0.0, 0.001, 0.0, 
                                            0.0, 0.0, 0.001]