# Example parameters for a UART connection to the Easy IMU module.
eimu_ros:
  ros__parameters:
    serial_port: "/dev/ttyACM0"
    serial_baud_rate: 115200
    serial_timeout_ms: 16
    
    frame_id: "imu"
    publish_frequency: 50.0
    world_frame_id: 1  # 0 - NWU,  1 - ENU,  2 - NED
    publish_tf_on_map_frame: false

    use_static_covariances: false
    
    static_covariance_orientation: [1e-5, 0.0, 0.0, 
                                    0.0, 1e-5, 0.0, 
                                    0.0, 0.0, 1e-5]

    static_covariance_angular_velocity: [1e-5, 0.0, 0.0, 
                                         0.0, 1e-5, 0.0, 
                                         0.0, 0.0, 1e-5]

    static_covariance_linear_acceleration: [1e-5, 0.0, 0.0, 
                                            0.0, 1e-5, 0.0, 
                                            0.0, 0.0, 1e-5]